export const cakeData = [
  {
    name: "Rainbow Pinata",
    amount: 9800,
    inCart: false,
    count: 1,

    image: "cake-images/cake13.jpg",
    category: "birthday cake",
    _id: 1,
    customerFav: true,
    total: 0,
    newAmount: 9800,
  },
  {
    name: "Rainbow Pinata",
    amount: 7600,
    inCart: false,
    count: 1,
    image: "cake-images/cake3.jpg",
    category: "wedding cake",
    _id: 2,
    total: 0,
    newAmount: 7600,
  },
  {
    name: "Crispy cake",
    amount: 2800,
    inCart: false,
    count: 1,

    image: "cake-images/cake5.jpg",
    category: "children cake",
    _id: 3,
    customerFav: true,
    total: 0,
    newAmount: 2800,
  },
  {
    name: "Sponge Cake",
    amount: 11100,
    inCart: false,
    count: 1,
    image: "cake-images/cake6.jpg",
    category: "valentine cake",
    _id: 4,
    total: 0,
    newAmount: 11100,
  },
  {
    name: "Red Velvet Cupcake",
    amount: 2600,
    inCart: false,
    count: 1,
    image: "cake-images/cake7.jpg",

    category: "cup cake",
    _id: 5,
    customerFav: true,
    total: 0,
    newAmount: 2600,
  },
  {
    name: "donut",
    amount: 1000,
    inCart: false,
    count: 1,

    image: "cake-images/cake10.jpg",
    category: "donut",
    _id: 6,
    customerFav: true,
    total: 0,
    newAmount: 1000,
  },
  {
    name: "Sponge Cake",
    amount: 3600,
    inCart: false,
    count: 1,
    image: "cake-images/cake11.jpg",
    category: "valentine cake",
    _id: 7,
    total: 0,
    newAmount: 3600,
  },
  {
    name: "Coconut Cake",
    amount: 8600,
    inCart: false,
    count: 1,
    image: "cake-images/cake12.jpg",
    category: "birthday cake",
    _id: 8,
    customerFav: true,
    total: 0,
    newAmount: 8600,
  },
];

export const categoriesData =['Birthday Cake', 'Wedding Cake', "Valentine Cake", "Anniversary Cake", "Children's Cake",]